rST to markdown conversion
geeksforsocialchange/PlaceCal-Handbook-Old pull request #4
Opened 2022-01-19 17:58 UTC by ivankocienski

Using markdown as the document format. It's still a little sphinx dependent for doing fancy things like ToCs but that is minimal

2022-01-19 18:06 UTC, alexandria-gfsc commented on the-team.md
> +PlaceCal is developed by Geeks for Social Change and <mailto:PHASE@MMU>. It was
Not 100% sure that this shouldn't be an email link, however, it seems wrong in context haha

2022-01-19 18:07 UTC, alexandria-gfsc commented on introduction/philosophy.md
> +Change), Prof. Stefan White (<mailto:PHASE@MMU>) and the Manchester Age Friendly
I think the same thing happened here too

2022-01-19 18:08 UTC, alexandria-gfsc requested changes
looks good aside from those two mailto links tho! :+1:

2022-01-19 19:16 UTC, kimadactyl commented
Yep, not an email link but otherwise good!

2022-01-20 10:12 UTC, ivankocienski commented
These have been fixed now

2022-02-08 15:10 UTC, kimadactyl commented
Superceded by #6

2022-02-08 15:10 UTC, closed without merging